# -*- encoding: utf-8 -*-

=begin
#DEAR Inventory API

#This specifing endpoints for DEAR Inventory API

The version of the OpenAPI document: 2.0.0
Contact: nnhansg@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

$:.push File.expand_path("../lib", __FILE__)
require "dear-inventory-ruby/version"

Gem::Specification.new do |s|
  s.name        = "dear-inventory-ruby"
  s.version     = DearInventoryRuby::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Nhan Nguyen"]
  s.email       = ["nnhansg@gmail.com"]
  s.homepage    = "https://inventory.dearsystems.com"
  s.summary     = "DEAR Inventory Ruby SDK generated from DEAR-OpenAPI Spec 3.0 for https://inventory.dearsystems.com"
  s.description = "DEAR Inventory Ruby SDK generated from DEAR-OpenAPI Spec 3.0 for https://inventory.dearsystems.com"
  s.license     = 'MIT'
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'faraday', '>= 0.14.0'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
