=begin
#DEAR Inventory API

#This specifing endpoints for DEAR Inventory API

The version of the OpenAPI document: 2.0.0
Contact: nnhansg@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module DearInventoryRuby
  class AttributeSet
    # Unique Attribute Set identifier
    attr_accessor :id

    # Name of Attribute Set
    attr_accessor :name

    # Name of first attribute
    attr_accessor :attribute1_name

    # Type of first attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute1_type

    # Comma-separated list of values for first attribute (applicable when Type is List)
    attr_accessor :attribute1_values

    # Name of second attribute
    attr_accessor :attribute2_name

    # Type of second attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute2_type

    # Comma-separated list of values for second attribute (applicable when Type is List)
    attr_accessor :attribute2_values

    # Name of third attribute
    attr_accessor :attribute3_name

    # Type of third attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute3_type

    # Comma-separated list of values for third attribute (applicable when Type is List)
    attr_accessor :attribute3_values

    # Name of fourth attribute
    attr_accessor :attribute4_name

    # Type of fourth attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute4_type

    # Comma-separated list of values for fourth attribute (applicable when Type is List)
    attr_accessor :attribute4_values

    # Name of fifth attribute
    attr_accessor :attribute5_name

    # Type of fifth attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute5_type

    # Comma-separated list of values for fifth attribute (applicable when Type is List)
    attr_accessor :attribute5_values

    # Name of sixth attribute
    attr_accessor :attribute6_name

    # Type of sixth attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute6_type

    # Comma-separated list of values for sixth attribute (applicable when Type is List)
    attr_accessor :attribute6_values

    # Name of seventh attribute
    attr_accessor :attribute7_name

    # Type of seventh attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute7_type

    # Comma-separated list of values for seventh attribute (applicable when Type is List)
    attr_accessor :attribute7_values

    # Name of eighth attribute
    attr_accessor :attribute8_name

    # Type of eighth attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute8_type

    # Comma-separated list of values for eighth attribute (applicable when Type is List)
    attr_accessor :attribute8_values

    # Name of ninth attribute
    attr_accessor :attribute9_name

    # Type of ninth attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute9_type

    # Comma-separated list of values for ninth attribute (applicable when Type is List)
    attr_accessor :attribute9_values

    # Name of tenth attribute
    attr_accessor :attribute10_name

    # Type of tenth attribute. Should be one of the following values: `Text`, `List`, `Checkbox`, `Not used`, `Date`, `Numeric`
    attr_accessor :attribute10_type

    # Comma-separated list of values for tenth attribute (applicable when Type is List)
    attr_accessor :attribute10_values

    # Array of Attribute Set Attributes
    attr_accessor :attributes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'ID',
        :'name' => :'Name',
        :'attribute1_name' => :'Attribute1Name',
        :'attribute1_type' => :'Attribute1Type',
        :'attribute1_values' => :'Attribute1Values',
        :'attribute2_name' => :'Attribute2Name',
        :'attribute2_type' => :'Attribute2Type',
        :'attribute2_values' => :'Attribute2Values',
        :'attribute3_name' => :'Attribute3Name',
        :'attribute3_type' => :'Attribute3Type',
        :'attribute3_values' => :'Attribute3Values',
        :'attribute4_name' => :'Attribute4Name',
        :'attribute4_type' => :'Attribute4Type',
        :'attribute4_values' => :'Attribute4Values',
        :'attribute5_name' => :'Attribute5Name',
        :'attribute5_type' => :'Attribute5Type',
        :'attribute5_values' => :'Attribute5Values',
        :'attribute6_name' => :'Attribute6Name',
        :'attribute6_type' => :'Attribute6Type',
        :'attribute6_values' => :'Attribute6Values',
        :'attribute7_name' => :'Attribute7Name',
        :'attribute7_type' => :'Attribute7Type',
        :'attribute7_values' => :'Attribute7Values',
        :'attribute8_name' => :'Attribute8Name',
        :'attribute8_type' => :'Attribute8Type',
        :'attribute8_values' => :'Attribute8Values',
        :'attribute9_name' => :'Attribute9Name',
        :'attribute9_type' => :'Attribute9Type',
        :'attribute9_values' => :'Attribute9Values',
        :'attribute10_name' => :'Attribute10Name',
        :'attribute10_type' => :'Attribute10Type',
        :'attribute10_values' => :'Attribute10Values',
        :'attributes' => :'Attributes'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'attribute1_name' => :'String',
        :'attribute1_type' => :'String',
        :'attribute1_values' => :'String',
        :'attribute2_name' => :'String',
        :'attribute2_type' => :'String',
        :'attribute2_values' => :'String',
        :'attribute3_name' => :'String',
        :'attribute3_type' => :'String',
        :'attribute3_values' => :'String',
        :'attribute4_name' => :'String',
        :'attribute4_type' => :'String',
        :'attribute4_values' => :'String',
        :'attribute5_name' => :'String',
        :'attribute5_type' => :'String',
        :'attribute5_values' => :'String',
        :'attribute6_name' => :'String',
        :'attribute6_type' => :'String',
        :'attribute6_values' => :'String',
        :'attribute7_name' => :'String',
        :'attribute7_type' => :'String',
        :'attribute7_values' => :'String',
        :'attribute8_name' => :'String',
        :'attribute8_type' => :'String',
        :'attribute8_values' => :'String',
        :'attribute9_name' => :'String',
        :'attribute9_type' => :'String',
        :'attribute9_values' => :'String',
        :'attribute10_name' => :'String',
        :'attribute10_type' => :'String',
        :'attribute10_values' => :'String',
        :'attributes' => :'Array<AttributeSetAttribute>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DearInventoryRuby::AttributeSet` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DearInventoryRuby::AttributeSet`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'attribute1_name')
        self.attribute1_name = attributes[:'attribute1_name']
      end

      if attributes.key?(:'attribute1_type')
        self.attribute1_type = attributes[:'attribute1_type']
      end

      if attributes.key?(:'attribute1_values')
        self.attribute1_values = attributes[:'attribute1_values']
      end

      if attributes.key?(:'attribute2_name')
        self.attribute2_name = attributes[:'attribute2_name']
      end

      if attributes.key?(:'attribute2_type')
        self.attribute2_type = attributes[:'attribute2_type']
      end

      if attributes.key?(:'attribute2_values')
        self.attribute2_values = attributes[:'attribute2_values']
      end

      if attributes.key?(:'attribute3_name')
        self.attribute3_name = attributes[:'attribute3_name']
      end

      if attributes.key?(:'attribute3_type')
        self.attribute3_type = attributes[:'attribute3_type']
      end

      if attributes.key?(:'attribute3_values')
        self.attribute3_values = attributes[:'attribute3_values']
      end

      if attributes.key?(:'attribute4_name')
        self.attribute4_name = attributes[:'attribute4_name']
      end

      if attributes.key?(:'attribute4_type')
        self.attribute4_type = attributes[:'attribute4_type']
      end

      if attributes.key?(:'attribute4_values')
        self.attribute4_values = attributes[:'attribute4_values']
      end

      if attributes.key?(:'attribute5_name')
        self.attribute5_name = attributes[:'attribute5_name']
      end

      if attributes.key?(:'attribute5_type')
        self.attribute5_type = attributes[:'attribute5_type']
      end

      if attributes.key?(:'attribute5_values')
        self.attribute5_values = attributes[:'attribute5_values']
      end

      if attributes.key?(:'attribute6_name')
        self.attribute6_name = attributes[:'attribute6_name']
      end

      if attributes.key?(:'attribute6_type')
        self.attribute6_type = attributes[:'attribute6_type']
      end

      if attributes.key?(:'attribute6_values')
        self.attribute6_values = attributes[:'attribute6_values']
      end

      if attributes.key?(:'attribute7_name')
        self.attribute7_name = attributes[:'attribute7_name']
      end

      if attributes.key?(:'attribute7_type')
        self.attribute7_type = attributes[:'attribute7_type']
      end

      if attributes.key?(:'attribute7_values')
        self.attribute7_values = attributes[:'attribute7_values']
      end

      if attributes.key?(:'attribute8_name')
        self.attribute8_name = attributes[:'attribute8_name']
      end

      if attributes.key?(:'attribute8_type')
        self.attribute8_type = attributes[:'attribute8_type']
      end

      if attributes.key?(:'attribute8_values')
        self.attribute8_values = attributes[:'attribute8_values']
      end

      if attributes.key?(:'attribute9_name')
        self.attribute9_name = attributes[:'attribute9_name']
      end

      if attributes.key?(:'attribute9_type')
        self.attribute9_type = attributes[:'attribute9_type']
      end

      if attributes.key?(:'attribute9_values')
        self.attribute9_values = attributes[:'attribute9_values']
      end

      if attributes.key?(:'attribute10_name')
        self.attribute10_name = attributes[:'attribute10_name']
      end

      if attributes.key?(:'attribute10_type')
        self.attribute10_type = attributes[:'attribute10_type']
      end

      if attributes.key?(:'attribute10_values')
        self.attribute10_values = attributes[:'attribute10_values']
      end

      if attributes.key?(:'attributes')
        if (value = attributes[:'attributes']).is_a?(Array)
          self.attributes = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          attribute1_name == o.attribute1_name &&
          attribute1_type == o.attribute1_type &&
          attribute1_values == o.attribute1_values &&
          attribute2_name == o.attribute2_name &&
          attribute2_type == o.attribute2_type &&
          attribute2_values == o.attribute2_values &&
          attribute3_name == o.attribute3_name &&
          attribute3_type == o.attribute3_type &&
          attribute3_values == o.attribute3_values &&
          attribute4_name == o.attribute4_name &&
          attribute4_type == o.attribute4_type &&
          attribute4_values == o.attribute4_values &&
          attribute5_name == o.attribute5_name &&
          attribute5_type == o.attribute5_type &&
          attribute5_values == o.attribute5_values &&
          attribute6_name == o.attribute6_name &&
          attribute6_type == o.attribute6_type &&
          attribute6_values == o.attribute6_values &&
          attribute7_name == o.attribute7_name &&
          attribute7_type == o.attribute7_type &&
          attribute7_values == o.attribute7_values &&
          attribute8_name == o.attribute8_name &&
          attribute8_type == o.attribute8_type &&
          attribute8_values == o.attribute8_values &&
          attribute9_name == o.attribute9_name &&
          attribute9_type == o.attribute9_type &&
          attribute9_values == o.attribute9_values &&
          attribute10_name == o.attribute10_name &&
          attribute10_type == o.attribute10_type &&
          attribute10_values == o.attribute10_values &&
          attributes == o.attributes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, attribute1_name, attribute1_type, attribute1_values, attribute2_name, attribute2_type, attribute2_values, attribute3_name, attribute3_type, attribute3_values, attribute4_name, attribute4_type, attribute4_values, attribute5_name, attribute5_type, attribute5_values, attribute6_name, attribute6_type, attribute6_values, attribute7_name, attribute7_type, attribute7_values, attribute8_name, attribute8_type, attribute8_values, attribute9_name, attribute9_type, attribute9_values, attribute10_name, attribute10_type, attribute10_values, attributes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        DearInventoryRuby.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
