=begin
#DEAR Inventory API

#This specifing endpoints for DEAR Inventory API

The version of the OpenAPI document: 2.0.0
Contact: nnhansg@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'date'

module DearInventoryRuby
  class DimensionsUnit
    M = "m".freeze
    CM = "cm".freeze
    MI = "mi".freeze
    MM = "mm".freeze
    IN = "in".freeze
    FT = "ft".freeze
    YD = "yd".freeze
    KM = "km".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = DimensionsUnit.constants.select { |c| DimensionsUnit::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #DimensionsUnit" if constantValues.empty?
      value
    end
  end
end
