=begin
#DEAR Inventory API

#This specifing endpoints for DEAR Inventory API

The version of the OpenAPI document: 2.0.0
Contact: nnhansg@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'date'

module DearInventoryRuby
  class WeightUnit
    OZ = "oz".freeze
    MG = "mg".freeze
    KG = "kg".freeze
    LB = "lb".freeze
    G = "g".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = WeightUnit.constants.select { |c| WeightUnit::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #WeightUnit" if constantValues.empty?
      value
    end
  end
end
