=begin
#DEAR Inventory API

#This specifing endpoints for DEAR Inventory API

The version of the OpenAPI document: 2.0.0
Contact: nnhansg@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'cgi'

module DearRuby
  class CustomerApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Allows you to retrieve the customers
    # @param [Hash] opts the optional parameters
    # @option opts [String] :page Default is 1 (default to '1')
    # @option opts [String] :limit Default is 100 (default to '100')
    # @option opts [String] :id Default is null
    # @option opts [String] :name Default is null
    # @option opts [String] :modified_since Default is null
    # @option opts [String] :include_deprecated Default is false (default to 'false')
    # @return [Customers]
    def get_customers(opts = {})
      data, _status_code, _headers = get_customers_with_http_info(opts)
      data
    end

    # Allows you to retrieve the customers
    # @param [Hash] opts the optional parameters
    # @option opts [String] :page Default is 1
    # @option opts [String] :limit Default is 100
    # @option opts [String] :id Default is null
    # @option opts [String] :name Default is null
    # @option opts [String] :modified_since Default is null
    # @option opts [String] :include_deprecated Default is false
    # @return [Array<(Customers, Integer, Hash)>] Customers data, response status code and response headers
    def get_customers_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CustomerApi.get_customers ...'
      end
      # resource path
      local_var_path = '/customer'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'Page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'Limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'ID'] = opts[:'id'] if !opts[:'id'].nil?
      query_params[:'Name'] = opts[:'name'] if !opts[:'name'].nil?
      query_params[:'ModifiedSince'] = opts[:'modified_since'] if !opts[:'modified_since'].nil?
      query_params[:'IncludeDeprecated'] = opts[:'include_deprecated'] if !opts[:'include_deprecated'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] 

      # return_type
      return_type = opts[:return_type] || 'Customers' 

      # auth_names
      auth_names = opts[:auth_names] || ['accountID', 'appKey']

      new_options = opts.merge(
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CustomerApi#get_customers\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
