=begin
#DEAR Inventory API

#This specifing endpoints for DEAR Inventory API

The version of the OpenAPI document: 2.0.0
Contact: nnhansg@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'dear-inventory-ruby/api_client'
require 'dear-inventory-ruby/api_error'
require 'dear-inventory-ruby/version'
require 'dear-inventory-ruby/configuration'

# Models
require 'dear-inventory-ruby/models/account'
require 'dear-inventory-ruby/models/accounts'
require 'dear-inventory-ruby/models/address'
require 'dear-inventory-ruby/models/contact'
require 'dear-inventory-ruby/models/currency_code'
require 'dear-inventory-ruby/models/customer'
require 'dear-inventory-ruby/models/customers'
require 'dear-inventory-ruby/models/dimensions_unit'
require 'dear-inventory-ruby/models/error'
require 'dear-inventory-ruby/models/me'
require 'dear-inventory-ruby/models/payment_term'
require 'dear-inventory-ruby/models/payment_terms'
require 'dear-inventory-ruby/models/price_tier'
require 'dear-inventory-ruby/models/price_tiers'
require 'dear-inventory-ruby/models/sale_invoice'
require 'dear-inventory-ruby/models/sale_invoice_additional_charge'
require 'dear-inventory-ruby/models/sale_invoice_line'
require 'dear-inventory-ruby/models/sale_invoices'
require 'dear-inventory-ruby/models/success'
require 'dear-inventory-ruby/models/tax'
require 'dear-inventory-ruby/models/tax_component'
require 'dear-inventory-ruby/models/taxes'

# APIs
require 'dear-inventory-ruby/api/inventory_api'

module DearInventoryRuby
  class << self
    # Customize default settings for the SDK using block.
    #   DearInventoryRuby.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
